server:
  port: 2020
  
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update        
    defer-datasource-initialization: true
    properties:
      hibernate:
         show_sql: true
         format_sql: true
         
  mvc:
    view:
      prefix: /views/
      suffix: .jsp